services:
    app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=start_tec_senai
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - CORS_ORIGINS=http://localhost:3001,http://localhost:5173
            - SESSION_CLEANUP_DAYS=90
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/app
            - /app/node_modules
        restart: unless-stopped
        command: sh -c "sleep 5 && npm run db:migrate && npm start"

    db:
        image: postgres:15
        environment:
            - POSTGRES_DB=start_tec_senai
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d start_tec_senai"]
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped

volumes:
    postgres_data:
